### ISSUE TITLE
PHP 8 ErrorException: Required parameter follows optional parameter

### ISSUE THREAD

**Issue by Pen-y-Fan** [delight-im/PHP-Str#2]
When running under PHP 8 I have the following error:

```sh
ErrorException: Required parameter $alwaysRemoveWhitespace follows optional parameter $charactersToRemove

/vendor/delight-im/str/src/Str.php:720
```

The fix is simple, remove the first "optional" parameter. The method class is called from three places, all three pass in the two required parameters.

```diff
- private function trimInternal(callable $func, $charactersToRemove = null, $alwaysRemoveWhitespace) {
+ private function trimInternal(callable $func, $charactersToRemove, $alwaysRemoveWhitespace) {
```

I'm happy to create PR.

**Comment by ocram** [comment]
Thank you for this perfect bug report!

I’m really sorry it took so long.

A fix should be available in `v2.4.1`, which you can update to. Please let me know if that resolves the issue.

**Comment by Pen-y-Fan** [comment]
Many thanks, this is working perfectly in PHP8 👍🏼

**Comment by ocram** [comment]
Thank *you* for bringing this up!
